name: deploy
on:
  push:
    branches:
      - master
jobs:
  doc-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          persist-credentials: false
      - name: setup-ocaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.10.0
      - name: setup-deploy
        run: |
          opam pin add . -y --no-action
          opam depext -y toml toml_cconv
          opam install -y ./*.opam --deps-only --with-test --with-doc
          opam upgrade --fixup
          touch doc/.nojekyll
      - name: api
        run: |
          opam exec -- dune build @doc
          mv _build/default/_doc/_html doc/api
      - name: coverage
        run: |
          opam exec -- dune runtest --instrument-with bisect_ppx
          opam exec -- bisect-ppx-report html -o doc/coverage
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/
          CLEAN: true
